/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package golfApp.com;

/**
 *
 * @author mike
 */
public class HSGolfSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form HSGolfSubPanel
     */
    public HSGolfSubPanel() {
        initComponents();
    }
    
     
     public void setSubTitle(String t){
         subTitleLbl.setText(t);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subTitleLbl = new javax.swing.JLabel();
        createMenuBtn = new javax.swing.JRadioButton();
        updateMenuBtn = new javax.swing.JRadioButton();
        readMenuBtn = new javax.swing.JRadioButton();
        deleteMenuBtn = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        subTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitleLbl.setText("Sub Title");

        createMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createMenuBtn.setText("Create");

        updateMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateMenuBtn.setText("Update");

        readMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        readMenuBtn.setText("Read");

        deleteMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteMenuBtn.setText("Delete");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Launch Admin Operation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(createMenuBtn)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subTitleLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(readMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(updateMenuBtn)
                        .addGap(70, 70, 70)
                        .addComponent(deleteMenuBtn)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(subTitleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMenuBtn)
                    .addComponent(updateMenuBtn)
                    .addComponent(readMenuBtn)
                    .addComponent(deleteMenuBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton createMenuBtn;
    private javax.swing.JRadioButton deleteMenuBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton readMenuBtn;
    private javax.swing.JLabel subTitleLbl;
    private javax.swing.JRadioButton updateMenuBtn;
    // End of variables declaration//GEN-END:variables
}
