/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package golfApp.com;

/**
 *
 * @author mike
 */
public class HSGolfSubPanel extends javax.swing.JPanel {

    private String operation;
    
    
    /**
     * Creates new form HSGolfSubPanel
     */
    public HSGolfSubPanel() {
        initComponents();
        operation = "";
        
    }
    
     
     public void setSubTitle(String t){
         subTitleLbl.setText(t);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subTitleLbl = new javax.swing.JLabel();
        createMenuBtn = new javax.swing.JRadioButton();
        updateMenuBtn = new javax.swing.JRadioButton();
        readMenuBtn = new javax.swing.JRadioButton();
        deleteMenuBtn = new javax.swing.JRadioButton();
        launchAdminBtn = new javax.swing.JButton();

        subTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitleLbl.setText("Sub Title");

        createMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createMenuBtn.setText("Create");
        createMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuBtnActionPerformed(evt);
            }
        });

        updateMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateMenuBtn.setText("Update");
        updateMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuBtnActionPerformed(evt);
            }
        });

        readMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        readMenuBtn.setText("Read");
        readMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMenuBtnActionPerformed(evt);
            }
        });

        deleteMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteMenuBtn.setText("Delete");
        deleteMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuBtnActionPerformed(evt);
            }
        });

        launchAdminBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        launchAdminBtn.setText("Launch Admin Operation");
        launchAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(createMenuBtn)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subTitleLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(launchAdminBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(readMenuBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(updateMenuBtn)
                        .addGap(70, 70, 70)
                        .addComponent(deleteMenuBtn)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(subTitleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createMenuBtn)
                    .addComponent(updateMenuBtn)
                    .addComponent(readMenuBtn)
                    .addComponent(deleteMenuBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(launchAdminBtn)
                .addGap(0, 167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuBtnActionPerformed
        // TODO add your handling code here:
        deleteMenuBtn.setSelected(false);
        updateMenuBtn.setSelected(false);
        readMenuBtn.setSelected(false);
         
    }//GEN-LAST:event_createMenuBtnActionPerformed

    private void readMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMenuBtnActionPerformed
        // TODO add your handling code here:
        deleteMenuBtn.setSelected(false);
        updateMenuBtn.setSelected(false);
        createMenuBtn.setSelected(false);
    }//GEN-LAST:event_readMenuBtnActionPerformed

    private void updateMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuBtnActionPerformed
        // TODO add your handling code here:
        deleteMenuBtn.setSelected(false);
        readMenuBtn.setSelected(false);
        createMenuBtn.setSelected(false);
    }//GEN-LAST:event_updateMenuBtnActionPerformed

    private void deleteMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuBtnActionPerformed
        // TODO add your handling code here:
        readMenuBtn.setSelected(false);
        updateMenuBtn.setSelected(false);
        createMenuBtn.setSelected(false);
    }//GEN-LAST:event_deleteMenuBtnActionPerformed

    private void launchAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchAdminBtnActionPerformed
        // TODO add your handling code here:
        if(readMenuBtn.isSelected()){
           setOperation("read");
           HSGolfMain.setDisplayType("read");
        }else if(createMenuBtn.isSelected()){
            setOperation("create");
        }else if(updateMenuBtn.isSelected()){
            setOperation("update");
        }else if(deleteMenuBtn.isSelected()){
            setOperation("delete");
        }
        
    }//GEN-LAST:event_launchAdminBtnActionPerformed

    public String getOperation(){
        return operation;
    }
    
    public void setOperation(String s){
        operation = s;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton createMenuBtn;
    private javax.swing.JRadioButton deleteMenuBtn;
    private javax.swing.JButton launchAdminBtn;
    private javax.swing.JRadioButton readMenuBtn;
    private javax.swing.JLabel subTitleLbl;
    private javax.swing.JRadioButton updateMenuBtn;
    // End of variables declaration//GEN-END:variables
}
